[package]
name = "triton"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
cgmath = "0.18"
log = "0.4.17"
log4rs = "1.2.0"
tracing = "0.1.40"
tracy-client = "0.16.4"
tracing-tracy = "0.10.4"
tracing-subscriber = "0.3.18"
vulkano = { path = "./vulkano/vulkano" }
vulkano-shaders = { path = "./vulkano/vulkano-shaders" }
vulkano-win = { path = "./vulkano/vulkano-win" }
vulkano-util = { path = "./vulkano/vulkano-util" }
winit = "0.29.3"

[features]
default = []
tracing = []
