[package]
name = "triton"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
cgmath = "0.18"
log = "0.4.17"
log4rs = "1.2.0"
tracing = "0.1.37"
tracy-client = "0.15.2"
tracing-tracy = "0.10.2"
tracing-subscriber = "0.3.0"
vulkano = { path = "./vulkano/vulkano" }
vulkano-shaders = { path = "./vulkano/vulkano-shaders"}
vulkano-win = { path = "./vulkano/vulkano-win" }
vulkano-util = { path = "./vulkano/vulkano-util" }
examples = { path = "./vulkano/examples"}
winit = "0.28.3"

[features]
default = ["tracing"]
tracing = []
