[package]
name = "triton"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies]
anyhow = "1.0.70"
log = "0.4.17"
log4rs = "1.2.0"
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.3"
game-loop = { path = "../game-loop" }